name: CI

on:
  push:
    branches: [ master ]
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  check-tools:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check tools
        run: make check-tools
  # test1:
  #   runs-on: self-hosted
  #
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: test1
  #       run: make test1
  test2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: test2
        run: make test2
